export const enum NodeType
{
    space,
    planet,
    unreachable, // for astroids/stars/spacestation
    nebula,
    cannon,
    orbit
}

export interface NodeDescription
{
    type: NodeType;
    name?: string;
}

export const template: NodeDescription[][] = [
    //0
    [{ type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.planet, name: "BlueRed"},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.unreachable},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.unreachable},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.unreachable},
     { type: NodeType.space}],
    //1
    [{ type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.orbit},
     { type: NodeType.orbit},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.orbit},
     { type: NodeType.unreachable},
     { type: NodeType.orbit},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.orbit},
     { type: NodeType.orbit},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space}],
    //2
    [{ type: NodeType.nebula},
     { type: NodeType.nebula},
     { type: NodeType.nebula},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.planet, name: "PinkSaturn"},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space}],
    //3
    [{ type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.planet, name: "GreenBall"},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space}],
    //4
    [{ type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.cannon},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.planet, name: "IceBall"},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space}],
    //5
    [{ type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.planet, name: "BlackGold"},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.planet, name: "FuzzyOrange"},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space}]
]