export const enum NodeType
{
    unreachable = "unreachable", // for astroids/stars/spacestation
    space = "space",
    planet = "planet",
    nebula = "nebula",
    cannon = "cannon",
    orbit = "orbit"
}

export const enum PlanetTypes
{
    BlueRed = "BlueRed",
    PinkSaturn = "PinkSaturn",
    GreenBall = "GreenBall",
    IceBall = "IceBall",
    BlackGold = "BlackGold",
    FuzzyOrange = "FuzzyOrange",
    WaterWorld = "WaterWorld",
    FuzzyIce = "FuzzyIce",
    YellowJupiter = "YellowJupiter",
    PurpleEye = "PurpleEye"
}

export interface NodeDescription
{
    type: NodeType;
    name?: PlanetTypes;
}

export const template: NodeDescription[][] = [
    //0
    [{ type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.orbit},
    { type: NodeType.orbit},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.orbit},
    { type: NodeType.unreachable},
    { type: NodeType.orbit},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.orbit},
    { type: NodeType.orbit},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space}],
    //1
    [{ type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.planet, name: PlanetTypes.BlueRed},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.unreachable},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.unreachable},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.unreachable},
    { type: NodeType.space}],
    //2
    [{ type: NodeType.nebula},
     { type: NodeType.nebula},
     { type: NodeType.nebula},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.planet, name: PlanetTypes.PinkSaturn},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space}],
    //3
    [{ type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.planet, name: PlanetTypes.GreenBall },
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space}],
    //4
    [{ type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.cannon},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.planet, name: PlanetTypes.IceBall },
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.space},
     { type: NodeType.unreachable},
     { type: NodeType.space},
     { type: NodeType.space}],
    //5
    [{ type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.planet, name: PlanetTypes.BlackGold },
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.planet, name: PlanetTypes.FuzzyOrange },
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space}],
    //6
    [{ type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.unreachable},
    { type: NodeType.planet, name: PlanetTypes.WaterWorld},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space}],
    //7
    [{ type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.planet, name: PlanetTypes.FuzzyIce},
    { type: NodeType.space}],
    //8
    [{ type: NodeType.space},
    { type: NodeType.nebula},
    { type: NodeType.nebula},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.planet, name: PlanetTypes.YellowJupiter},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.space}],
    //9
    [{ type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.planet, name: PlanetTypes.PurpleEye},
    { type: NodeType.space},
    { type: NodeType.unreachable},
    { type: NodeType.unreachable},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.space},
    { type: NodeType.unreachable}]
]